services:
    _defaults:
        public: true

    gearman.taskmanager: '@GearmanBundle\TaskManager\TaskManager'
    app.metric.controller: '@DatabaseBundle\Controller\Api\V1\NoSql\MetricController'
    nosql.metric.repository: '@DatabaseBundle\NoSql\Metric\MetricRepository'
    nosql.database.connection.provider: '@DatabaseBundle\NoSql\DatabaseConnectionProvider'
    app.system.parameter_resolver: '@DataSourceBundle\Api\V1\DataSourceCollect\ParametersResolver'
    app.system.collect.controller: '@DataSourceBundle\Controller\Api\V1\System\DataSourceCollectController'
    data.source.api.v1.mapper: '@DataSourceBundle\Mapper\Api\V1\ResponseMapper'
    app.doctrine.data.source.uid.generator: '@DataSourceBundle\Doctrine\DataSourceCollectUidListener'
    app.region_provider: '@DataSourceBundle\Entity\Aws\Region\RegionProvider'
    array.mapper: '@EssentialsBundle\ArrayMapper'
    account.register: '@EssentialsBundle\Register\Account'
    account.account_builder: '@EssentialsBundle\Entity\Account\AccountBuilder'
    error.dispatcher: '@EssentialsBundle\Exception\Dispatcher'
    app.api.v1.account.controller: '@EssentialsBundle\Controller\Api\V1\AccountController'
    profiler_subscriber: '@EssentialsBundle\EventListener\ProfilerDeathSubscriber'
    timeperiods: '@EssentialsBundle\Entity\TimePeriod\TimePeriodProvider'
    timeperiod_provider: '@EssentialsBundle\Entity\TimePeriod\TimePeriodProvider'
    app.mutex: '@EssentialsBundle\MutexProvider\MutexProvider'
    api.security.token_authenticator: '@EssentialsBundle\Api\ApiKeyAuthenticator'
    cache.factory: '@EssentialsBundle\Cache\CacheFactory'
    exception_subscriber: '@EssentialsBundle\EventListener\AuthExceptionSubscriber'
    auth_exception_subscriber: '@EssentialsBundle\EventListener\ExceptionSubscriber'
    app.security.access_denied_handler: '@EssentialsBundle\Api\ApiAccessDeniedHandler'
    mail_helper: '@EssentialsBundle\Helpers\MailHelper'
    app.security.login_form_authenticator: '@FrontendBundle\Security\LoginFormAuthenticator'
    app.doctrine.hash_password_listener: '@FrontendBundle\Doctrine\HashPasswordListener'
    app.doctrine.account_uid_generator: '@FrontendBundle\Doctrine\AccountUidListener'
    collector.collect.job.builder: '@CollectorBundle\Job\JobBuilder'
    discovery.api.mapper: '@CollectorBundle\Mapper\Discovery\ApiMapper'
    collect.bucket.builder: '@CollectorBundle\Collect\CollectBucketBuilder'
    collect.processor: '@CollectorBundle\Processor\Processor'
    collect.result.sender: '@CollectorBundle\Collector\ResultSender'